# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20160207_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to=b'announcements/')),
            ],
            options={
                'ordering': ('-date',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='hoppyupdate',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
