# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20160207_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='hoppyupdate',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
    ]
