# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to=b'announcements/')),
            ],
            options={
                'ordering': ('-date',),
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'events/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to=b'gallery_covers', verbose_name=b'Cover Image')),
            ],
            options={
                'ordering': ('-date',),
                'get_latest_by': 'date',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=b'gallery_images')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='HoppyUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to=b'hoppy_updates/')),
            ],
            options={
                'ordering': ('-date',),
                'get_latest_by': 'date',
                'verbose_name_plural': 'Hoppy Updates',
            },
        ),
        migrations.CreateModel(
            name='NewspaperArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=b'newspapers')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Newspaper Archive',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'banner_ads')),
                ('link', models.URLField(blank=True, null=True)),
                ('in_credits', models.BooleanField(default=False, verbose_name=b'include in credits')),
                ('in_ads', models.BooleanField(default=False, verbose_name=b'include in banner ads')),
            ],
        ),
    ]
