# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_gallery_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=b'banner_ads')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'get_latest_by': 'date', 'ordering': ('-date',), 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='hoppyupdate',
            options={'get_latest_by': 'date', 'ordering': ('-date',), 'verbose_name_plural': 'Hoppy Updates'},
        ),
    ]
