# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20160210_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banneradvertisement',
            options={'verbose_name': 'Banner Ad', 'verbose_name_plural': 'Banner Ads'},
        ),
    ]
