# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20160213_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewspaperArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=b'newspapers')),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'Newspaper Archive',
            },
        ),
    ]
