# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_newspaperarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaperarchive',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
