# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20160221_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerAdvertisement',
            new_name='Partner',
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
    ]
