# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20160224_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
