# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
