# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20160224_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='in_ads',
            field=models.BooleanField(default=False, verbose_name=b'include in banner ads'),
        ),
        migrations.AddField(
            model_name='partner',
            name='in_credits',
            field=models.BooleanField(default=False, verbose_name=b'include in credits'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'banner_ads'),
        ),
    ]
